name: PR Auto-merge

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write

jobs:
  call:
    uses: aws/agentcore-devx-devtools/.github/workflows/reusable-pr-automerge.yml@458c0a684af0f9e3a013ec05cd23851def4f9cab
    secrets: inherit
