name: PR Size and Title

on:
  pull_request_target:
    branches: [main, feat/**]
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  call:
    uses: aws/agentcore-devx-devtools/.github/workflows/reusable-pr-size-title.yml@458c0a684af0f9e3a013ec05cd23851def4f9cab
    with:
      runner: ubuntu
    secrets: inherit
