name: Sync From Public

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  call:
    uses: aws/agentcore-devx-devtools/.github/workflows/reusable-sync-from-public.yml@458c0a684af0f9e3a013ec05cd23851def4f9cab
    secrets: inherit
